default-config-set: hybrid

#deletes regions in worlds that no longer exist
delete-invalid-regions: false
black-list-worlds:
  - Hub

default-language: en
line-break-length: 40
line-break-length-per-language:
  en: 40
  zh: 25

##should region upkeeps be on standby when empty
##turning on this setting may cause lag
region-standby: false

##Do not enable this unless you have tested it
##It basically allows people to bypass limits and dupe civ items with min amounts (like shelter)
allow-civ-item-sharing: false

##Show player skins in menu icons
show-player-skins-in-menus: true

##Allows players to set bounties on each other and on towns
use-bounties: true

#allows players to earn exp in skills
allow-skills: true
#turns off exp chat notifications for skills
no-exp-chat-messages: false

##put rings above towns
town-rings: true
town-ring-material: "GLOWSTONE"
town-rings-crumble-to-gravel: true

##how long a town sits at zero before protection ends
##if destroy towns at zero is on, then this does nothing
town-grace-period: 0 #no grace period

##ignore other plugins when checking if an explosion is cancelled
##before reducing power
explosion-override: false

destroy-towns-at-zero: false #should towns be destroyed if at zero power

##Should chunks containing region chests be loaded at all times
keep-region-chunks-loaded: true
disable-regions-in-unloaded-chunks: false
##how often (minutes) should unloaded chunks be loaded to update chests?
##higher number means less lag, lower number means potential item loss in the event of a crash
unloaded-chest-refresh-rate: 10

## the max amount that an owner can tax per day of each town member (only certain gov types)
max-town-tax: 100.0
## the max amount that can be in a town bank (excluding taxes)
max-bank-deposit: -1

min-distance-between-towns: 10

use-starter-book: true

##whether or not the glass box should appear to show the region's boundaries
use-region-bounding-box: true
##should region dimensions be shown with particles instead of glass?
use-particle-bounding-boxes: false

price-multiplier: 1.0 #multiplier for prices before adding base price
price-base: 0.0 #added to all item prices

exp-base: 100
exp-modifier: 0.2

jail-time-seconds: 300

##cooldown before spawning a new villager in seconds
villager-cooldown: 300

##Allow people to hunt other players in other worlds
allow-hunt-cross-world: false

##stops arrow turrets from shooting at monsters
disable-arrow-turret-shooting-at-mobs: false

##mobs killed in safe zones will not drop items
stop-mobs-from-dropping-items-in-safe-zones: false

##cooldown in seconds before killing the same player reduces the town power
death-grace-period-seconds: 60
##how many seconds a player is considered in combat after taking or dealing damage
combat-tag-duration: 60
##how much damage should a player receive if they log out during combat
combat-log-out-percent-damage: 80

##should food heal in combat?
allow-food-heal-in-combat: true
##should players be able to teleport while in combat?
allow-teleporting-during-combat: false

##can a raidporter be built to raid a town with no online members
allow-offline-raiding: true
##can non-allied players teleport out of towns?
allow-teleporting-out-of-hostile-towns: true

##use the class and spell system from Civs
##this is an undocumented and unfinished feature
use-classes-and-spells: false

##Should the town enter and exit messages be titles (or chat)
enter-exit-messages-use-titles: true

points:
  killstreak: 0.1
  killjoy: 0.2
  kill: 1
  death: -1
  half-health: 0.5
  quarter-health: 1
money:
  killstreak: 10
  killjoy: 10
  kill: 100
  karma: 0.2
hardship-per-kill: 500
karma-per-kill: 50
karma-per-kill-streak: 5
##How often should karma be cut by 50%? Adds 50% to negative karma. Subtracts 50% from positive karma.
karma-depreciate-period: 43200 #12 hours
hardship-should-pay-damages: true
hardship-depreciation-period-in-days: 7 #once a week
hunt-karma: 250.0 # how much karma should a town get when using a building with hunt
hunt-new-players: true # should players be able to hunt people that aren't in towns
##Should money be created if it can't be taken from the victim
always-drop-money-if-no-balance: false
power-per-kill: 30
power-per-npc-kill: 5

folders:
  farms: STONE_HOE
  towns:
    icon: GLOWSTONE
    pre-reqs:
      - population=1|built=command_tent|built=council_room|built=town_hall|built=city_hall|built=capitol
  shops: EMERALD
  utilities: REDSTONE
  housing:
    icon: RED_BED
    pre-reqs:
      - member=settlement:hamlet:village:town:city:metropolis
  defense:
    icon: ARROW
    pre-reqs:
      - population=1
  quarries: STONE_SHOVEL
  factories: PISTON
  offense: TNT
  mines: STONE_PICKAXE
  woodworks: OAK_LOG
  hyphaeworks: CRIMSON_STEM
  animals: SHEEP_SPAWN_EGG
  npchousing: VILLAGER_SPAWN_EGG
  trading:
    icon: EMERALD_ORE
    pre-reqs:
      - member=hamlet:village:town:city:metropolis

levels:
  - DIRT
  - OAK_LOG
  - COAL_BLOCK
  - IRON_BLOCK
  - GOLD_BLOCK
  - EMERALD_BLOCK
  - DIAMOND_BLOCK

item-groups:
  sign: OAK_SIGN,OAK_WALL_SIGN,BIRCH_SIGN,BIRCH_WALL_SIGN,SPRUCE_SIGN,SPRUCE_WALL_SIGN,DARK_OAK_SIGN,DARK_OAK_WALL_SIGN,ACACIA_SIGN,ACACIA_WALL_SIGN,JUNGLE_SIGN,JUNGLE_WALL_SIGN,CRIMSON_SIGN,CRIMSON_WALL_SIGN,WARPED_SIGN,WARPED_WALL_SIGN
  wool: RED_WOOL,BLACK_WOOL,BLUE_WOOL,BROWN_WOOL,CYAN_WOOL,GRAY_WOOL,GREEN_WOOL,LIGHT_BLUE_WOOL,LIGHT_GRAY_WOOL,LIME_WOOL,MAGENTA_WOOL,ORANGE_WOOL,PINK_WOOL,PURPLE_WOOL,WHITE_WOOL,YELLOW_WOOL
  carpet: WHITE_CARPET,ORANGE_CARPET,MAGENTA_CARPET,LIGHT_BLUE_CARPET,YELLOW_CARPET,LIME_CARPET,PINK_CARPET,GRAY_CARPET,LIGHT_GRAY_CARPET,CYAN_CARPET,PURPLE_CARPET,BLUE_CARPET,BROWN_CARPET,GREEN_CARPET,RED_CARPET,BLACK_CARPET
  banners: WHITE_BANNER,ORANGE_BANNER,MAGENTA_BANNER,LIGHT_BLUE_BANNER,YELLOW_BANNER,LIME_BANNER,PINK_BANNER,GRAY_BANNER,LIGHT_GRAY_BANNER,CYAN_BANNER,PURPLE_BANNER,BLUE_BANNER,BROWN_BANNER,GREEN_BANNER,RED_BANNER,BLACK_BANNER,WHITE_WALL_BANNER,ORANGE_WALL_BANNER,MAGENTA_WALL_BANNER,LIGHT_BLUE_WALL_BANNER,YELLOW_WALL_BANNER,LIME_WALL_BANNER,PINK_WALL_BANNER,GRAY_WALL_BANNER,LIGHT_GRAY_WALL_BANNER,CYAN_WALL_BANNER,PURPLE_WALL_BANNER,BLUE_WALL_BANNER,BROWN_WALL_BANNER,GREEN_WALL_BANNER,RED_WALL_BANNER,BLACK_WALL_BANNER
  wood: OAK_PLANKS,SPRUCE_PLANKS,BIRCH_PLANKS,JUNGLE_PLANKS,DARK_OAK_PLANKS,ACACIA_PLANKS,CRIMSON_PLANKS,WARPED_PLANKS
  stripped_wood: STRIPPED_OAK_WOOD,STRIPPED_SPRUCE_WOOD,STRIPPED_BIRCH_WOOD,STRIPPED_JUNGLE_WOOD,STRIPPED_DARK_OAK_WOOD,STRIPPED_ACACIA_WOOD
  wood_slab: OAK_SLAB,BIRCH_SLAB,SPRUCE_SLAB,JUNGLE_SLAB,ACACIA_SLAB,DARK_OAK_SLAB,CRIMSON_SLAB,WARPED_SLAB
  log: OAK_LOG,SPRUCE_LOG,BIRCH_LOG,JUNGLE_LOG,DARK_OAK_LOG,ACACIA_LOG,OAK_WOOD,SPRUCE_WOOD,BIRCH_WOOD,JUNGLE_WOOD,DARK_OAK_WOOD,ACACIA_WOOD,CRIMSON_STEM,CRIMSON_HYPHAE,WARPED_STEM,WARPED_HYPHAE
  stripped_log: STRIPPED_OAK_LOG,STRIPPED_SPRUCE_LOG,STRIPPED_BIRCH_LOG,STRIPPED_JUNGLE_LOG,STRIPPED_DARK_OAK_LOG,STRIPPED_ACACIA_LOG,STRIPPED_OAK_WOOD,STRIPPED_SPRUCE_WOOD,STRIPPED_BIRCH_WOOD,STRIPPED_JUNGLE_WOOD,STRIPPED_DARK_OAK_WOOD,STRIPPED_ACACIA_WOOD,STRIPPED_CRIMSON_STEM,STRIPPED_CRIMSON_HYPHAE,STRIPPED_WARPED_STEM,STRIPPED_WARPED_HYPHAE
  leaves: OAK_LEAVES,SPRUCE_LEAVES,BIRCH_LEAVES,JUNGLE_LEAVES,DARK_OAK_LEAVES,ACACIA_LEAVES,NETHER_WART_BLOCK,WARPED_WART_BLOCK
  fence: OAK_FENCE,BIRCH_FENCE,SPRUCE_FENCE,JUNGLE_FENCE,DARK_OAK_FENCE,ACACIA_FENCE,IRON_BARS,MOSSY_COBBLESTONE_WALL,COBBLESTONE_WALL,NETHER_BRICK_FENCE,CRIMSON_FENCE,WARPED_FENCE
  fencegate: OAK_FENCE_GATE,BIRCH_FENCE_GATE,SPRUCE_FENCE_GATE,JUNGLE_FENCE_GATE,DARK_OAK_FENCE_GATE,ACACIA_FENCE_GATE,CRIMSON_FENCE_GATE,WARPED_FENCE_GATE
  door: OAK_DOOR,ACACIA_DOOR,DARK_OAK_DOOR,SPRUCE_DOOR,BIRCH_DOOR,JUNGLE_DOOR,IRON_DOOR,CRIMSON_DOOR,WARPED_DOOR
  trapdoor: OAK_TRAPDOOR,SPRUCE_TRAPDOOR,BIRCH_TRAPDOOR,JUNGLE_TRAPDOOR,DARK_OAK_TRAPDOOR,ACACIA_TRAPDOOR,IRON_TRAPDOOR,CRIMSON_TRAPDOOR,WARPED_TRAPDOOR
  glass: g:glass_block,g:glass_pane
  glass_block: GLASS,RED_STAINED_GLASS,BLACK_STAINED_GLASS,BLUE_STAINED_GLASS,BROWN_STAINED_GLASS,CYAN_STAINED_GLASS,GRAY_STAINED_GLASS,GREEN_STAINED_GLASS,LIGHT_BLUE_STAINED_GLASS,LIGHT_GRAY_STAINED_GLASS,LIME_STAINED_GLASS,MAGENTA_STAINED_GLASS,ORANGE_STAINED_GLASS,PINK_STAINED_GLASS,PURPLE_STAINED_GLASS,WHITE_STAINED_GLASS,YELLOW_STAINED_GLASS
  glass_pane: GLASS_PANE,RED_STAINED_GLASS_PANE,BLACK_STAINED_GLASS_PANE,BLUE_STAINED_GLASS_PANE,BROWN_STAINED_GLASS_PANE,CYAN_STAINED_GLASS_PANE,GRAY_STAINED_GLASS_PANE,GREEN_STAINED_GLASS_PANE,LIGHT_BLUE_STAINED_GLASS_PANE,LIGHT_GRAY_STAINED_GLASS_PANE,LIME_STAINED_GLASS_PANE,MAGENTA_STAINED_GLASS_PANE,ORANGE_STAINED_GLASS_PANE,PINK_STAINED_GLASS_PANE,PURPLE_STAINED_GLASS_PANE,WHITE_STAINED_GLASS_PANE,YELLOW_STAINED_GLASS_PANE
  terracotta: TERRACOTTA,RED_TERRACOTTA,BLACK_TERRACOTTA,BLUE_TERRACOTTA,BROWN_TERRACOTTA,CYAN_TERRACOTTA,GRAY_TERRACOTTA,GREEN_TERRACOTTA,LIGHT_BLUE_TERRACOTTA,LIGHT_GRAY_TERRACOTTA,LIME_TERRACOTTA,MAGENTA_TERRACOTTA,ORANGE_TERRACOTTA,PINK_TERRACOTTA,PURPLE_TERRACOTTA,WHITE_TERRACOTTA,YELLOW_TERRACOTTA
  glazed_terracotta: RED_GLAZED_TERRACOTTA,BLACK_GLAZED_TERRACOTTA,BLUE_GLAZED_TERRACOTTA,BROWN_GLAZED_TERRACOTTA,CYAN_GLAZED_TERRACOTTA,GRAY_GLAZED_TERRACOTTA,GREEN_GLAZED_TERRACOTTA,LIGHT_BLUE_GLAZED_TERRACOTTA,LIGHT_GRAY_GLAZED_TERRACOTTA,LIME_GLAZED_TERRACOTTA,MAGENTA_GLAZED_TERRACOTTA,ORANGE_GLAZED_TERRACOTTA,PINK_GLAZED_TERRACOTTA,PURPLE_GLAZED_TERRACOTTA,WHITE_GLAZED_TERRACOTTA,YELLOW_GLAZED_TERRACOTTA
  window: g:glass,NETHER_BRICK_FENCE,OAK_FENCE,BIRCH_FENCE,SPRUCE_FENCE,JUNGLE_FENCE,DARK_OAK_FENCE,ACACIA_FENCE,IRON_BARS
  primary: g:wood,g:stripped_wood,CLAY,SMOOTH_SANDSTONE,SMOOTH_RED_SANDSTONE,STONE_BRICKS,QUARTZ_BLOCK,PACKED_ICE,g:wool,g:terracotta,PRISMARINE,PURPUR_BLOCK,NETHER_BRICKS,POLISHED_ANDESITE,POLISHED_DIORITE,POLISHED_GRANITE
  secondary: COBBLESTONE,g:log,g:stripped_log,g:concrete,SANDSTONE,RED_SANDSTONE,BRICKS,MOSSY_COBBLESTONE,SNOW_BLOCK,QUARTZ_PILLAR,CHISELED_QUARTZ_BLOCK,g:glazed_terracotta,DARK_PRISMARINE,PURPUR_PILLAR
  roof: g:stairs,g:wood_slab,QUARTZ_SLAB
  bed: RED_BED,BLACK_BED,BLUE_BED,BROWN_BED,CYAN_BED,GRAY_BED,GREEN_BED,LIGHT_BLUE_BED,LIGHT_GRAY_BED,LIME_BED,MAGENTA_BED,ORANGE_BED,PINK_BED,PURPLE_BED,WHITE_BED,YELLOW_BED
  stairs: QUARTZ_STAIRS,SANDSTONE_STAIRS,RED_SANDSTONE_STAIRS,ACACIA_STAIRS,OAK_STAIRS,BIRCH_STAIRS,JUNGLE_STAIRS,SPRUCE_STAIRS,DARK_OAK_STAIRS,BRICK_STAIRS,COBBLESTONE_STAIRS,DARK_PRISMARINE_STAIRS,PRISMARINE_BRICK_STAIRS,PURPUR_STAIRS,STONE_BRICK_STAIRS,QUARTZ_STAIRS,CRIMSON_STAIRS,WARPED_STAIRS
  vertical: LADDER,g:stairs
  concrete: WHITE_CONCRETE,ORANGE_CONCRETE,MAGENTA_CONCRETE,LIGHT_BLUE_CONCRETE,YELLOW_CONCRETE,LIME_CONCRETE,PINK_CONCRETE,GRAY_CONCRETE,LIGHT_GRAY_CONCRETE,CYAN_CONCRETE,PURPLE_CONCRETE,BLUE_CONCRETE,BROWN_CONCRETE,GREEN_CONCRETE,RED_CONCRETE,BLACK_CONCRETE
  concrete_powder: WHITE_CONCRETE_POWDER,ORANGE_CONCRETE_POWDER,MAGENTA_CONCRETE_POWDER,LIGHT_BLUE_CONCRETE_POWDER,YELLOW_CONCRETE_POWDER,LIME_CONCRETE_POWDER,PINK_CONCRETE_POWDER,GRAY_CONCRETE_POWDER,LIGHT_GRAY_CONCRETE_POWDER,CYAN_CONCRETE_POWDER,PURPLE_CONCRETE_POWDER,BLUE_CONCRETE_POWDER,BROWN_CONCRETE_POWDER,GREEN_CONCRETE_POWDER,RED_CONCRETE_POWDER,BLACK_CONCRETE_POWDER
  rails: RAIL,POWERED_RAIL,DETECTOR_RAIL,ACTIVATOR_RAIL
  circuits: REDSTONE_WIRE,REDSTONE_BLOCK,REPEATER,COMPARATOR,REDSTONE_TORCH,REDSTONE_WALL_TORCH
  triggers: g:button,g:pressure_plates
  button: STONE_BUTTON,OAK_BUTTON,SPRUCE_BUTTON,BIRCH_BUTTON,JUNGLE_BUTTON,DARK_OAK_BUTTON,ACACIA_BUTTON,CRIMSON_BUTTON,WARPED_BUTTON,POLISHED_BLACKSTONE_BUTTON
  pressure_plates: STONE_PRESSURE_PLATE,OAK_PRESSURE_PLATE,SPRUCE_PRESSURE_PLATE,BIRCH_PRESSURE_PLATE,JUNGLE_PRESSURE_PLATE,DARK_OAK_PRESSURE_PLATE,ACACIA_PRESSURE_PLATE,CRIMSON_PRESSURE_PLATE,WARPED_PRESSURE_PLATE,POLISHED_BLACKSTONE_PRESSURE_PLATE,LIGHT_WEIGHTED_PRESSURE_PLATE,HEAVY_WEIGHTED_PRESSURE_PLATE
  tables: CRAFTING_TABLE,SMITHING_TABLE,FLETCHING_TABLE,ENCHANTING_TABLE
  job_blocks: LECTERN,COMPOSTER,GRINDSTONE,BLAST_FURNACE,SMOKER,FLETCHING_TABLE,CARTOGRAPHY_TABLE,BREWING_STAND,SMITHING_TABLE,CAULDRON,BARREL,LOOM,STONECUTTER
  furnaces: SMOKER,BLAST_FURNACE,FURNACE
  forge: SMITHING_TABLE,GRINDSTONE,ANVIL,CHIPPED_ANVIL,DAMAGED_ANVIL,BLAST_FURNACE,FURNACE
  storage: CHEST,BARREL,TRAPPED_CHEST,ENDER_CHEST,SHULKER_BOX,WHITE_SHULKER_BOX,ORANGE_SHULKER_BOX,MAGENTA_SHULKER_BOX,LIGHT_BLUE_SHULKER_BOX,YELLOW_SHULKER_BOX,LIME_SHULKER_BOX,PINK_SHULKER_BOX,GRAY_SHULKER_BOX,LIGHT_GRAY_SHULKER_BOX,CYAN_SHULKER_BOX,PURPLE_SHULKER_BOX,BLUE_SHULKER_BOX,BROWN_SHULKER_BOX,GREEN_SHULKER_BOX,RED_SHULKER_BOX,BLACK_SHULKER_BOX
  bees: BEE_NEST,BEEHIVE,CAMPFIRE,SOUL_CAMPFIRE
  alchemy: BREWING_STAND,CAULDRON,BARREL
  light: TORCH,WALL_TORCH,SOUL_TORCH,SOUL_WALL_TORCH,LANTERN,SOUL_LANTERN,CAMPFIRE,SOUL_CAMPFIRE,GLOWSTONE,SEA_LANTERN,REDSTONE_LAMP,SHROOMLIGHT,END_ROD
  walls: COBBLESTONE_WALL,MOSSY_COBBLESTONE_WALL,BRICK_WALL,PRISMARINE_WALL,RED_SANDSTONE_WALL,MOSSY_STONE_BRICK_WALL,GRANITE_WALL,STONE_BRICK_WALL,NETHER_BRICK_WALL,ANDESITE_WALL,RED_NETHER_BRICK_WALL,SANDSTONE_WALL,END_STONE_BRICK_WALL,DIORITE_WALL,BLACKSTONE_WALL,POLISHED_BLACKSTONE_WALL,POLISHED_BLACKSTONE_BRICK_WALL
  nether_blocks: NETHERRACK,CRIMSON_NYLIUM,WARPED_NYLIUM,SOUL_SAND,SOUL_SOIL,BASALT,POLISHED_BASALT,BLACKSTONE_WALL,POLISHED_BLACKSTONE_WALL,POLISHED_BLACKSTONE_BRICK_WALL,NETHER_BRICK_FENCE,NETHER_BRICK_WALL,RED_NETHER_BRICK_WALL,BLACKSTONE,BLACKSTONE_SLAB,BLACKSTONE_STAIRS,POLISHED_BLACKSTONE,POLISHED_BLACKSTONE_SLAB,POLISHED_BLACKSTONE_STAIRS,CHISELED_POLISHED_BLACKSTONE,POLISHED_BLACKSTONE_BRICKS,POLISHED_BLACKSTONE_BRICK_SLAB,POLISHED_BLACKSTONE_BRICK_STAIRS,CRACKED_POLISHED_BLACKSTONE_BRICKS,NETHER_BRICKS,CRACKED_NETHER_BRICKS,CHISELED_NETHER_BRICKS,NETHER_BRICK_STAIRS,NETHER_BRICK_SLAB,RED_NETHER_BRICKS,RED_NETHER_BRICK_STAIRS,RED_NETHER_BRICK_SLAB,NETHER_WART_BLOCK,CRIMSON_STEM,STRIPPED_CRIMSON_STEM,CRIMSON_HYPHAE,STRIPPED_CRIMSON_HYPHAE,WARPED_WART_BLOCK,WARPED_STEM,STRIPPED_WARPED_STEM,WARPED_HYPHAE,STRIPPED_WARPED_HYPHAE,GLOWSTONE,SHROOMLIGHT
  quartz_blocks: QUARTZ_BLOCK,QUARTZ_BRICKS,QUARTZ_PILLAR,QUARTZ_SLAB,QUARTZ_STAIRS,CHISELED_QUARTZ_BLOCK,SMOOTH_QUARTZ,SMOOTH_QUARTZ_SLAB,SMOOTH_QUARTZ_STAIRS
  sandstone: SANDSTONE,SANDSTONE_SLAB,SANDSTONE_STAIRS,SANDSTONE_WALL,SMOOTH_SANDSTONE,SMOOTH_SANDSTONE_SLAB,SMOOTH_SANDSTONE_STAIRS,CHISELED_SANDSTONE,CUT_SANDSTONE,CUT_SANDSTONE_SLAB,RED_SANDSTONE,RED_SANDSTONE_SLAB,RED_SANDSTONE_STAIRS,RED_SANDSTONE_WALL,SMOOTH_RED_SANDSTONE,SMOOTH_RED_SANDSTONE_SLAB,SMOOTH_RED_SANDSTONE_STAIRS,CHISELED_RED_SANDSTONE,CUT_RED_SANDSTONE,CUT_RED_SANDSTONE_SLAB
  stone_bricks: STONE_BRICKS,MOSSY_STONE_BRICKS,CHISELED_STONE_BRICKS,CRACKED_STONE_BRICKS,STONE_BRICK_SLAB,STONE_BRICK_STAIRS,STONE_BRICK_WALL,MOSSY_STONE_BRICK_SLAB,MOSSY_STONE_BRICK_STAIRS,MOSSY_STONE_BRICK_WALL
  flowers: DANDELION,POPPY,BLUE_ORCHID,ALLIUM,AZURE_BLUET,RED_TULIP,ORANGE_TULIP,WHITE_TULIP,PINK_TULIP,OXEYE_DAISY,CORNFLOWER,LILY_OF_THE_VALLEY,WITHER_ROSE,SUNFLOWER,LILAC,ROSE_BUSH,PEONY
  plants: GRASS,FERN,DEAD_BUSH,SEAGRASS,SEA_PICKLE,BROWN_MUSHROOM,RED_MUSHROON,CRIMSON_FUNGUS,WARPED_FUNGUS,CRIMSON_ROOTS,WARPED_ROOTS,NETHER_SPROUTS,WEEPING_VINES,TWISTING_VINES,SUGAR_CANE,KELP,BAMBOO,VINE,LILY_PAD,TALL_GRASS,LARGE_FERN,CACTUS

groups:
  shop: 3
  quarry: 12
  housing: 3

##region port configs
port:
  mana: 0
  warmup: 5
  cooldown: 60
  money: 0
  damage: 0
  stamina: 0
  port-during-combat: false
  #list of items needed but not consumed
  #reagents: []
  slow-warmup: true

tutorial:
  use-tutorial: true
  use-guide: true
top-guide-spacer: "-----------------Civs-----------------"
bottom-guide-spacer: "--------------------------------------"
civs-chat-prefix: "@{GREEN}[Civs]"
prefix-all-text: ""
civs-item-prefix: "Civs"

chat-channel-format: "[$channel$]$player$: $message$"
chat-channels:
  global:
    enabled: true
    icon: ENDER_CHEST
  local:
    enabled: true
    icon: GRASS
  friend:
    enabled: true
    icon: PLAYER_HEAD
  town:
    enabled: true
    icon: BRICKS
  nation:
    enabled: true
    icon: BLUE_BANNER
  alliance:
    enabled: true
    icon: GOLDEN_SWORD

allow-changing-gov-type: true
default-gov-type: "DICTATORSHIP"
# how many players need to be in a town before the gov type will auto transition
# on new days
min-population-for-auto-gov-transition: 4
## for governments that use voting, for how long should a player be elected?
days-between-elections: 7
use-announcements: true
announcement-period: 240

## do not turn this on unless you want to spam your console with potentially useless info
debug-log: false

# How long should invaders sit in an uncontested alliance claim (16x16) before neutralizing it
# Setting this to -1 disables the claim timer
alliance-claim-capture-seconds: 180
# The material needed to capture new alliance claims
claim-material: REDSTONE*8
# How much power should an alliance have per land claim
power-per-nation-claim: 1
# When the nation is created from an alliance, it will attempt to claim land so that the
# towns are connected by nation claims
use-claims-connect-towns-when-nation-created: true
unclaimed-icon: "GRASS_BLOCK"
nation-formed-at-town-level: 4
# Should TNT explosions unclaim nation chunks
unclaim-nation-chunks-with-tnt: true
nation-claim-effects:
  - "block_break"
  - "block_build"
  - "block_fire"
  - "block_explosion"
